[package]
name = "greed"
description = "A policy optimizer for the game of Greed."
version = "0.1.0"
edition = "2024"
readme = "README.md"
license-file = "LICENSE"
repository = "https://github.com/pure-chance/greed"
keywords = ["statistics", "analysis", "optimization"]
categories = ["mathematics", "algorithms", "simulation"]

[dependencies]
csv = "1.3.0"
clap = "4.5.36"
rayon = "1.10.0"

[dev-dependencies]
criterion = "0.8.2"

[profile.profile]
inherits = "release"
debug = true

[lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"
cargo = "warn"

[[bench]]
name = "pmf"
harness = false

[[bench]]
name = "terminal"
harness = false

[[bench]]
name = "normal"
harness = false

[[bench]]
name = "solve"
harness = false
